POST http://localhost:3333/events
Content-Type: application/json

{
  "title" : "Novo evento 2",
  "details" : null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/d6347339-a70d-4917-8bca-6806e84ac637/attendees
Content-Type: application/json

{
  "name" : "Paulo Alves",
  "email" : "ph22223.alves@gmail.com"
}

###

GET http://localhost:3333/events/d6347339-a70d-4917-8bca-6806e84ac637
